export const SHOW_ALL = 'show_all'
export const SHOW_COMPLETED = 'show_completed'
export const SHOW_ACTIVE = 'show_active'
export const SHOW_HIGH = 'SHOW_HIGH'
export const SHOW_MEDIUM = 'show_medium'
export const SHOW_LOW = 'show_low'