export const CREATE_DEVICE = "CREATE_DEVICE";
export const UPDATE_DEVICE = "UPDATE_DEVICE";
export const DELETE_DEVICE = "DELETE_DEVICE";
export const FETCH_DEVICES = "FETCH_DEVICES";
export const GET_ACTIVE_DEVICE_REQUEST = "GET_ACTIVE_DEVICE_REQUEST";
export const SET_ACTIVE_DEVICE_REQUEST = "SET_ACTIVE_DEVICE_REQUEST";
export const UPDATE_ACTIVE_DEVICE_REQUEST = "UPDATE_ACTIVE_DEVICE_REQUEST";